<?php

namespace Database\Seeders;

use App\Models\PetHistoryEvent;
use App\Models\PetHistoryPhrase;
use Illuminate\Database\Seeder;

class PetHistorySeeder extends Seeder
{
    public function run(): void
    {
        $actions = [
            'care.meal' => ['ru' => 'Кормление', 'en' => 'Feeding'],
            'care.water' => ['ru' => 'Вода', 'en' => 'Water'],
            'care.walk' => ['ru' => 'Прогулка', 'en' => 'Walk'],
            'care.home' => ['ru' => 'Прогулка у дома', 'en' => 'Walk near home'],
            'care.attention' => ['ru' => 'Внимание', 'en' => 'Attention'],
            'care.toy' => ['ru' => 'Игра с игрушкой', 'en' => 'Toy play'],
            'care.wash' => ['ru' => 'Мытьё', 'en' => 'Washing'],
            'care.care' => ['ru' => 'Уход за шерстью', 'en' => 'Grooming'],
            'care.nap' => ['ru' => 'Короткий отдых', 'en' => 'Nap'],
            'care.sleep' => ['ru' => 'Сон', 'en' => 'Sleep'],
            'training' => ['ru' => 'Тренировка', 'en' => 'Training'],
            'skill_training' => ['ru' => 'Обучение навыку', 'en' => 'Skill lesson'],
            'work' => ['ru' => 'Работа', 'en' => 'Work'],
            'veterinary.checkup' => ['ru' => 'Осмотр ветеринара', 'en' => 'Veterinary checkup'],
            'veterinary.treatment' => ['ru' => 'Лечение', 'en' => 'Treatment'],
            'veterinary.vaccination' => ['ru' => 'Прививка', 'en' => 'Vaccination'],
        ];
        foreach ($actions as $code => $name) {
            PetHistoryEvent::query()->firstOrCreate(['code' => $code], [
                'kind' => 'action', 'name' => $name, 'conditions' => [], 'is_active' => true,
            ]);
        }

        $thoughts = [
            ['thought.starving', ['ru' => 'Очень голоден', 'en' => 'Very hungry'], 1000, 60, [['field' => 'satiety', 'operator' => 'lt', 'value' => 15]], [['ru' => 'Хозяин, очень хочу есть! Миска совсем пустая.', 'en' => 'Human, I am really hungry! My bowl is empty.'], ['ru' => 'В животе урчит громче, чем я лаю. Покорми меня!', 'en' => 'My tummy is louder than my bark. Feed me!'], ['ru' => 'Можно ужин прямо сейчас? Я так проголодался!', 'en' => 'Can I have dinner right now? I am so hungry!']]],
            ['thought.hungry', ['ru' => 'Хочу есть', 'en' => 'Hungry'], 850, 120, [['field' => 'satiety', 'operator' => 'gte', 'value' => 15], ['field' => 'satiety', 'operator' => 'lt', 'value' => 35]], [['ru' => 'Хозяин, хочу есть. Давай заглянем к моей миске?', 'en' => 'Human, I am hungry. Shall we check my bowl?'], ['ru' => 'Кажется, пришло время вкусного обеда!', 'en' => 'I think it is time for a tasty lunch!'], ['ru' => 'Я уже представляю, как хрустит мой корм.', 'en' => 'I can already imagine my crunchy food.']]],
            ['thought.parched', ['ru' => 'Очень хочу пить', 'en' => 'Very thirsty'], 1050, 60, [['field' => 'hydration', 'operator' => 'lt', 'value' => 15]], [['ru' => 'Хозяин, мне срочно нужна вода!', 'en' => 'Human, I really need water!'], ['ru' => 'В миске ни капли. Нальёшь водички?', 'en' => 'There is not a drop in my bowl. Could you fill it?'], ['ru' => 'Язык совсем сухой. Давай скорее попьём!', 'en' => 'My tongue is so dry. Let us get a drink!']]],
            ['thought.thirsty', ['ru' => 'Хочу пить', 'en' => 'Thirsty'], 900, 120, [['field' => 'hydration', 'operator' => 'gte', 'value' => 15], ['field' => 'hydration', 'operator' => 'lt', 'value' => 35]], [['ru' => 'Хозяин, хочу пить. Где моя миска с водой?', 'en' => 'Human, I am thirsty. Where is my water bowl?'], ['ru' => 'После всех приключений неплохо бы попить.', 'en' => 'A drink would be nice after all our adventures.'], ['ru' => 'Свежая водичка сейчас была бы очень кстати.', 'en' => 'Some fresh water would be lovely right now.']]],
            ['thought.unwell', ['ru' => 'Плохо себя чувствую', 'en' => 'Feeling unwell'], 1100, 120, [['field' => 'health', 'operator' => 'lt', 'value' => 30]], [['ru' => 'Хозяин, мне нехорошо. Побудь рядом, пожалуйста.', 'en' => 'Human, I feel unwell. Please stay close.'], ['ru' => 'Сегодня совсем мало сил. Может, зайдём к ветеринару?', 'en' => 'I have little strength today. Could we see the vet?'], ['ru' => 'Что-то я не в форме. Мне нужна твоя забота.', 'en' => 'I do not feel like myself. I need your care.']]],
            ['thought.recovering', ['ru' => 'Нужно поберечься', 'en' => 'Need some care'], 800, 180, [['field' => 'health', 'operator' => 'gte', 'value' => 30], ['field' => 'health', 'operator' => 'lt', 'value' => 60]], [['ru' => 'Давай сегодня без спешки. Хочу немного поберечься.', 'en' => 'Let us take it easy today. I need a gentle day.'], ['ru' => 'Немного отдыха и заботы — и я снова буду бодрым!', 'en' => 'Some rest and care will help me feel better!'], ['ru' => 'Хозяин, посмотри, всё ли со мной хорошо?', 'en' => 'Human, could you check if I am all right?']]],
            ['thought.exhausted', ['ru' => 'Очень устал', 'en' => 'Exhausted'], 750, 120, [['field' => 'energy', 'operator' => 'lt', 'value' => 20]], [['ru' => 'Лапы совсем устали. Хочу поспать.', 'en' => 'My paws are so tired. I want to sleep.'], ['ru' => 'Можно свернуться клубочком и отдохнуть?', 'en' => 'Can I curl up and rest?'], ['ru' => 'Все приключения завтра. Сегодня мне нужен сон.', 'en' => 'Adventures can wait until tomorrow. I need sleep.']]],
            ['thought.tired', ['ru' => 'Пора отдохнуть', 'en' => 'Time to rest'], 600, 180, [['field' => 'energy', 'operator' => 'gte', 'value' => 20], ['field' => 'energy', 'operator' => 'lt', 'value' => 45]], [['ru' => 'Хозяин, давай сделаем паузу и отдохнём.', 'en' => 'Human, let us take a break and rest.'], ['ru' => 'Я немного устал. Моя лежанка уже зовёт.', 'en' => 'I am a little tired. My bed is calling.'], ['ru' => 'После отдыха у меня снова будут силы играть.', 'en' => 'After some rest I will have energy to play again.']]],
            ['thought.sad', ['ru' => 'Мне грустно', 'en' => 'Feeling sad'], 700, 180, [['field' => 'mood', 'operator' => 'lt', 'value' => 30]], [['ru' => 'Хозяин, мне грустно. Поиграешь со мной?', 'en' => 'Human, I feel sad. Will you play with me?'], ['ru' => 'Хвост что-то не хочет вилять. Давай повеселимся?', 'en' => 'My tail will not wag. Can we have some fun?'], ['ru' => 'Мне бы немного твоего внимания.', 'en' => 'I could use a little of your attention.']]],
            ['thought.bored', ['ru' => 'Мне скучно', 'en' => 'Bored'], 500, 180, [['field' => 'mood', 'operator' => 'gte', 'value' => 30], ['field' => 'mood', 'operator' => 'lt', 'value' => 55], ['field' => 'activity', 'operator' => 'eq', 'value' => 'idle']], [['ru' => 'Хозяин, скучно сидеть без дела. Давай поиграем!', 'en' => 'Human, sitting around is boring. Let us play!'], ['ru' => 'Может, достанем мою любимую игрушку?', 'en' => 'Shall we get my favourite toy?'], ['ru' => 'Я придумал игру: ты бросаешь, а я приношу!', 'en' => 'I have a game: you throw, I fetch!']]],
            ['thought.dirty', ['ru' => 'Пора помыться', 'en' => 'Need a wash'], 650, 180, [['field' => 'cleanliness', 'operator' => 'lt', 'value' => 30]], [['ru' => 'Кажется, я собрал всю грязь во дворе. Помоемся?', 'en' => 'I think I found all the mud outside. Shall we wash?'], ['ru' => 'Лапы грязные, зато приключение было отличным!', 'en' => 'My paws are muddy, but the adventure was great!'], ['ru' => 'Хозяин, помоги снова стать чистым и пушистым.', 'en' => 'Human, help me get clean and fluffy again.']]],
            ['thought.grooming_needed', ['ru' => 'Нужен уход', 'en' => 'Need grooming'], 350, 240, [['field' => 'cleanliness', 'operator' => 'gte', 'value' => 30], ['field' => 'cleanliness', 'operator' => 'lt', 'value' => 60]], [['ru' => 'Шерсть немного растрепалась. Причешешь меня?', 'en' => 'My fur is a little messy. Will you brush it?'], ['ru' => 'Кажется, пора привести себя в порядок.', 'en' => 'I think it is time to tidy up.'], ['ru' => 'Люблю, когда ты заботишься о моей шерсти.', 'en' => 'I love it when you look after my coat.']]],
            ['thought.lonely', ['ru' => 'Скучаю по тебе', 'en' => 'Missing you'], 680, 180, [['field' => 'bond', 'operator' => 'lt', 'value' => 30]], [['ru' => 'Хозяин, я по тебе скучаю. Побудь со мной.', 'en' => 'Human, I miss you. Spend some time with me.'], ['ru' => 'Я принёс тебе лапу. Можно немного ласки?', 'en' => 'Here is my paw. Can I have a little affection?'], ['ru' => 'Давай посидим рядом. Мне тебя не хватает.', 'en' => 'Let us sit together. I have been missing you.']]],
            ['thought.attention', ['ru' => 'Хочу внимания', 'en' => 'Want attention'], 320, 240, [['field' => 'bond', 'operator' => 'gte', 'value' => 30], ['field' => 'bond', 'operator' => 'lt', 'value' => 60], ['field' => 'activity', 'operator' => 'eq', 'value' => 'idle']], [['ru' => 'Хозяин, погладь меня за ушком!', 'en' => 'Human, scratch behind my ear!'], ['ru' => 'Смотри, какой я хороший. Обнимемся?', 'en' => 'Look how good I am. Can we cuddle?'], ['ru' => 'Я рядом. Может, уделишь мне минутку?', 'en' => 'I am right here. Could you spare me a moment?']]],
            ['thought.ill', ['ru' => 'Нужен ветеринар', 'en' => 'Need the vet'], 1080, 180, [['field' => 'has_disease', 'operator' => 'eq', 'value' => true]], [['ru' => 'Хозяин, кажется, я заболел. Помоги мне поправиться.', 'en' => 'Human, I think I am ill. Help me get better.'], ['ru' => 'Мне нужен доктор, а потом твои объятия.', 'en' => 'I need a doctor and then your cuddles.'], ['ru' => 'Давай навестим ветеринара. Хочу снова быть здоровым.', 'en' => 'Let us visit the vet. I want to be healthy again.']]],
            ['thought.eating', ['ru' => 'Вкусный обед', 'en' => 'Enjoying a meal'], 200, 60, [['field' => 'activity', 'operator' => 'eq', 'value' => 'feed']], [['ru' => 'Ням! Как же вкусно пахнет!', 'en' => 'Yum! That smells so good!'], ['ru' => 'Спасибо за обед, хозяин!', 'en' => 'Thank you for lunch, human!'], ['ru' => 'Сейчас поем — и можно снова исследовать мир.', 'en' => 'After this meal I can explore the world again.']]],
            ['thought.walking', ['ru' => 'На прогулке', 'en' => 'Out for a walk'], 210, 60, [['field' => 'activity', 'operator' => 'eq', 'value' => 'walk']], [['ru' => 'Столько интересных запахов! Хозяин, идём дальше!', 'en' => 'So many interesting smells! Human, let us keep going!'], ['ru' => 'Люблю наши прогулки. Смотри, что я нашёл!', 'en' => 'I love our walks. Look what I found!'], ['ru' => 'Свежий воздух, твои шаги рядом — вот это счастье.', 'en' => 'Fresh air and your footsteps beside me make me happy.']]],
            ['thought.training', ['ru' => 'На тренировке', 'en' => 'Training'], 220, 60, [['field' => 'activity', 'operator' => 'eq', 'value' => 'training']], [['ru' => 'Смотри, хозяин, я стараюсь!', 'en' => 'Look, human, I am doing my best!'], ['ru' => 'Ещё одно упражнение — и я стану сильнее!', 'en' => 'One more exercise will make me stronger!'], ['ru' => 'Хочу, чтобы ты мной гордился.', 'en' => 'I want you to be proud of me.']]],
            ['thought.working', ['ru' => 'Выполняю задание', 'en' => 'At work'], 230, 60, [['field' => 'activity', 'operator' => 'eq', 'value' => 'work']], [['ru' => 'Я на задании! Постараюсь всё сделать хорошо.', 'en' => 'I am on a job! I will do my best.'], ['ru' => 'Хозяин, можешь на меня положиться.', 'en' => 'Human, you can count on me.'], ['ru' => 'Пора показать, чему я научился!', 'en' => 'Time to show what I have learned!']]],
            ['thought.playing', ['ru' => 'Играю', 'en' => 'Playing'], 205, 60, [['field' => 'activity', 'operator' => 'eq', 'value' => 'play']], [['ru' => 'Ещё раз! Бросай игрушку ещё раз!', 'en' => 'Again! Throw the toy again!'], ['ru' => 'Это самая лучшая игра на свете!', 'en' => 'This is the best game in the world!'], ['ru' => 'Хозяин, догоняй! Только попробуй меня поймать!', 'en' => 'Human, chase me! Try to catch me!']]],
            ['thought.sleeping', ['ru' => 'Отдыхаю', 'en' => 'Resting'], 240, 120, [['field' => 'activity', 'operator' => 'eq', 'value' => 'sleep']], [['ru' => 'Можно я ещё чуть-чуть посплю?..', 'en' => 'Can I sleep just a little longer?..'], ['ru' => 'Мне снится большая поляна и ты рядом.', 'en' => 'I am dreaming of a big meadow with you beside me.'], ['ru' => 'Тихо-тихо. Я набираюсь сил для новых приключений.', 'en' => 'Shh. I am resting for our next adventure.']]],
            ['thought.grooming', ['ru' => 'Забота и чистота', 'en' => 'Being groomed'], 200, 60, [['field' => 'activity', 'operator' => 'eq', 'value' => 'groom']], [['ru' => 'Скоро буду самым чистым псом во дворе!', 'en' => 'Soon I will be the cleanest dog around!'], ['ru' => 'Щётка немного щекочет. Но мне нравится твоя забота.', 'en' => 'The brush tickles a little. I like your care.'], ['ru' => 'Спасибо, хозяин. Теперь шерсть будет мягкой.', 'en' => 'Thanks, human. My coat will be soft again.']]],
            ['thought.content', ['ru' => 'Всё хорошо', 'en' => 'Feeling content'], 50, 360, [['field' => 'health', 'operator' => 'gte', 'value' => 75], ['field' => 'satiety', 'operator' => 'gte', 'value' => 75], ['field' => 'hydration', 'operator' => 'gte', 'value' => 75], ['field' => 'mood', 'operator' => 'gte', 'value' => 75], ['field' => 'cleanliness', 'operator' => 'gte', 'value' => 75], ['field' => 'activity', 'operator' => 'eq', 'value' => 'idle'], ['field' => 'has_disease', 'operator' => 'eq', 'value' => false]], [['ru' => 'Хозяин, мне так хорошо рядом с тобой!', 'en' => 'Human, I feel so good with you!'], ['ru' => 'Миска полная, лапы чистые, а ты рядом. Отличный день!', 'en' => 'A full bowl, clean paws and you nearby. A lovely day!'], ['ru' => 'Хвост сам виляет. Спасибо, что заботишься обо мне.', 'en' => 'My tail is wagging on its own. Thank you for caring.']]],
            ['thought.energetic', ['ru' => 'Готов к приключениям', 'en' => 'Ready for adventures'], 80, 360, [['field' => 'energy', 'operator' => 'gte', 'value' => 85], ['field' => 'satiety', 'operator' => 'gte', 'value' => 50], ['field' => 'hydration', 'operator' => 'gte', 'value' => 50], ['field' => 'health', 'operator' => 'gte', 'value' => 60], ['field' => 'activity', 'operator' => 'eq', 'value' => 'idle']], [['ru' => 'Хозяин, у меня столько сил! Пойдём гулять?', 'en' => 'Human, I have so much energy! Shall we go for a walk?'], ['ru' => 'Готов бегать, прыгать и учиться новому!', 'en' => 'I am ready to run, jump and learn new things!'], ['ru' => 'Лапы сами несут к двери. Нас ждут приключения!', 'en' => 'My paws are heading for the door. Adventure is waiting!']]],
            ['thought.affectionate', ['ru' => 'Рад быть рядом', 'en' => 'Happy to be close'], 70, 360, [['field' => 'bond', 'operator' => 'gte', 'value' => 85], ['field' => 'mood', 'operator' => 'gte', 'value' => 60], ['field' => 'activity', 'operator' => 'eq', 'value' => 'idle']], [['ru' => 'Ты мой самый любимый человек, хозяин.', 'en' => 'You are my favourite human.'], ['ru' => 'Давай просто побудем рядом. Так уютно.', 'en' => 'Let us just stay close. It feels so cosy.'], ['ru' => 'Я всегда рад тебя видеть. Даже если ты отошёл на минуту!', 'en' => 'I am always happy to see you, even after just a minute!']]],
        ];
        foreach ($thoughts as [$code, $name, $priority, $cooldown, $conditions, $phrases]) {
            $event = PetHistoryEvent::query()->firstOrCreate(['code' => $code], [
                'kind' => 'thought', 'name' => $name, 'priority' => $priority,
                'cooldown_minutes' => $cooldown, 'conditions' => $conditions, 'is_active' => true,
            ]);
            foreach ($phrases as $order => $text) {
                PetHistoryPhrase::query()->firstOrCreate(['pet_history_event_id' => $event->id, 'sort_order' => $order], [
                    'text' => $text, 'is_active' => true,
                ]);
            }
        }
    }
}
