<?php

return [
    'daily_kibble' => ['bonuses' => ['satiety' => 4], 'granted_effects' => ['slow_digest']],
    'beef_treats' => ['bonuses' => ['mood' => 8, 'bond' => 2], 'granted_effects' => ['eager', 'food_motivation']],
    'salmon_menu' => ['bonuses' => ['satiety' => 8], 'granted_effects' => ['energized', 'balanced_fuel']],
    'everyday_collar' => ['bonuses' => ['mood' => 3], 'granted_effects' => ['familiar_scent']],
    'woven_collar' => ['bonuses' => ['mood' => 8], 'granted_effects' => ['easy_movement']],
    'leather_collar' => ['bonuses' => ['mood' => 5], 'granted_effects' => ['comfortable', 'steady_rhythm']],
    'walking_leash' => ['bonuses' => ['bond' => 2], 'granted_effects' => ['steady_rhythm']],
    'long_leash' => ['bonuses' => ['mood' => 7], 'granted_effects' => ['adventure_memory']],
    'retractable_leash' => ['bonuses' => ['bond' => 4], 'granted_effects' => ['comfortable', 'close_companion']],
    'soft_brush' => ['bonuses' => ['bond' => 3], 'granted_effects' => ['silky_coat']],
    'gentle_shampoo' => ['bonuses' => ['cleanliness' => 10], 'granted_effects' => ['clean_barrier']],
    'grooming_set' => ['bonuses' => ['cleanliness' => 5], 'granted_effects' => ['relaxed', 'spa_calm']],
    'rubber_ball' => ['bonuses' => ['mood' => 4], 'granted_effects' => ['play_memory']],
    'rope_toy' => ['bonuses' => ['bond' => 5], 'granted_effects' => ['close_companion']],
    'snuffle_mat' => ['bonuses' => ['mood' => 3], 'granted_effects' => ['relaxed', 'focused', 'mental_map']],
    'sage_bandana' => ['bonuses' => ['bond' => 3], 'granted_effects' => ['cozy']],
    'raincoat' => ['bonuses' => ['cleanliness' => 10], 'granted_effects' => ['rain_protection', 'clean_barrier']],
    'knitted_sweater' => ['bonuses' => ['mood' => 3], 'granted_effects' => ['comfortable', 'cozy']],
    'training_cones' => ['bonuses' => ['bond' => 3], 'granted_effects' => ['focused', 'mental_map']],
    'agility_bar' => ['bonuses' => ['mood' => 8], 'granted_effects' => ['muscle_memory']],
    'agility_tunnel' => ['bonuses' => ['bond' => 2], 'granted_effects' => ['relaxed', 'coordination']],
];
